SHOW DATABASES;

USE CREDITO;
SHOW TABLES;

DESC CREDITO_ARQ_2;
SELECT * FROM CREDITO_ARQ_2 LIMIT 5;

CREATE TABLE CUBO AS SELECT 
	(CASE WHEN IDADE < 20 THEN 'JOVEM ADULTO_CRIANÇA' 
		 WHEN IDADE < 60 THEN 'ADULTO' ELSE 'IDOSO' END) AS FAIXA_IDADE
	,FAIXA_MESES_RELACIONAMENTO
    ,FAIXA_INATIVIDADE
    ,DS_CARTAO
    ,ESCOLARIDADE
    ,(CASE WHEN DEPENDENTES <= 2 THEN '<= 2 DEPENDENTES' ELSE '> 3 DEPENDENTES' END) AS FAIXA_DEPENDENTES
FROM CREDITO_ARQ_2
GROUP BY FAIXA_IDADE, FAIXA_MESES_RELACIONAMENTO, FAIXA_INATIVIDADE, DS_CARTAO, ESCOLARIDADE, FAIXA_DEPENDENTES
;

/* TRANSFORMANDO 10K DE LINHAS EM 190*/
SELECT * FROM CUBO;


